In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('../data/raw/Total-Supermarket-Sales.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              10000 non-null  str
 1   City              10000 non-null  str
 2   Country           10000 non-null  str
 3   Customer Type     10000 non-null  str
 4   Gender            10000 non-null  str
 5   Product Category  10000 non-null  str
 6   Product           10000 non-null  str
 7   SKU               10000 non-null  int64
 8   Unit Cost         10000 non-null  int64
 9   Sales Price       10000 non-null  int64
 10  Quantity          10000 non-null  int64
 11  COGS              10000 non-null  int64
 12  Discount          10000 non-null  float64
 13  Payment Method    10000 non-null  str
 14  Revenue           10000 non-null  float64
 15  Profit            10000 non-null  float64
dtypes: float64(3), int64(5), str(8)
memory usage: 1.8 MB

In [4]:
df.shape

(10000, 16)

In [5]:
df.isnull().sum()

Date                0
City                0
Country             0
Customer Type       0
Gender              0
Product Category    0
Product             0
SKU                 0
Unit Cost           0
Sales Price         0
Quantity            0
COGS                0
Discount            0
Payment Method      0
Revenue             0
Profit              0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
# Convert Date to datetime
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

# Check the data type
df["Date"].dtype

C:\Users\HP\AppData\Local\Temp\ipykernel_23296\3756665177.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

dtype('<M8[us]')

In [8]:
df["Date"].isnull().sum()

np.int64(0)

In [9]:
df.describe()

,Date,SKU,Unit Cost,Sales Price,Quantity,COGS,Discount,Revenue,Profit
count,10000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.00000,10000.000000
mean,2024-12-29 17:58:59.520000,1023.770000,3139.434200,4081.318400,5.20760,16236.526000,584.740428,20620.99799,4384.471990
min,2024-06-29 00:00:00,1000.000000,3.000000,4.000000,1.00000,3.000000,0.252000,3.60000,0.600000
25%,2024-09-30 00:00:00,1010.000000,55.000000,72.000000,4.00000,240.000000,23.400000,310.50000,60.000000
50%,2024-12-31 00:00:00,1023.000000,140.000000,182.000000,5.00000,720.000000,74.940000,910.00000,189.000000
75%,2025-03-29 00:00:00,1032.000000,1200.000000,1560.000000,7.00000,5400.000000,156.000000,6630.00000,1440.000000
max,2025-06-29 00:00:00,1058.000000,55000.000000,71500.000000,10.00000,550000.000000,10725.000000,715000.00000,165000.000000
std,NaN,15.481837,9381.424229,12195.833732,2.20186,53530.394838,1791.818955,67962.38489,14620.011434

In [10]:
df.head(10)

,Date,City,Country,Customer Type,Gender,Product Category,Product,SKU,Unit Cost,Sales Price,Quantity,COGS,Discount,Payment Method,Revenue,Profit
0,2024-06-29,Seattle,USA,Normal,Male,Groceries,Coffee (200g),1033,250,325,6,1500,100.00,Credit Card,1950.0,450.0
1,2024-06-29,Sheffield,UK,Member,Male,Groceries,Fruits,1024,80,104,9,720,93.60,Cash,936.0,216.0
2,2024-06-29,Kanpur,India,Normal,Female,Personal Care,Shampoo,1051,180,234,1,180,16.38,Credit Card,234.0,54.0
3,2024-06-29,Raichur,India,Normal,Male,Groceries,Energy Drink,1034,100,130,7,700,42.00,Cash,840.0,140.0
4,2024-06-29,Milwaukee,USA,Normal,Male,Groceries,Bread,1022,40,52,3,120,7.80,Cash,156.0,36.0
5,2024-06-29,Las Vegas,USA,Normal,Male,Groceries,Energy Drink,1034,100,130,6,600,39.00,Cash,780.0,180.0
6,2024-06-29,Austin,USA,Normal,Female,Personal Care,Shampoo,1051,180,234,7,1260,81.90,Cash,1638.0,378.0
7,2024-06-29,San Diego,USA,Normal,Female,Groceries,Fruits,1024,80,104,3,240,31.20,E-Wallet,312.0,72.0
8,2024-06-29,Kolhapur,India,Normal,Male,Groceries,Juice (1L),1032,90,117,6,540,49.14,Credit Card,702.0,162.0
9,2024-06-29,Umm Al Quwain,UAE,Normal,Male,Groceries,Packaged Water (1L),1031,20,26,5,100,8.40,Credit Card,120.0,20.0

In [11]:
df[[
    "Unit Cost",
    "Sales Price",
    "Quantity",
    "COGS",
    "Discount",
    "Revenue",
    "Profit"
]].head(10)

   Unit Cost  Sales Price  Quantity  COGS  Discount  Revenue  Profit
0        250          325         6  1500    100.00   1950.0   450.0
1         80          104         9   720     93.60    936.0   216.0
2        180          234         1   180     16.38    234.0    54.0
3        100          130         7   700     42.00    840.0   140.0
4         40           52         3   120      7.80    156.0    36.0
5        100          130         6   600     39.00    780.0   180.0
6        180          234         7  1260     81.90   1638.0   378.0
7         80          104         3   240     31.20    312.0    72.0
8         90          117         6   540     49.14    702.0   162.0
9         20           26         5   100      8.40    120.0    20.0

In [12]:
df[[
    "Unit Cost",
    "Sales Price",
    "Quantity",
    "COGS",
    "Discount",
    "Revenue",
    "Profit"
]].corr().round(2)

             Unit Cost  Sales Price  Quantity  COGS  Discount  Revenue  Profit
Unit Cost         1.00         1.00     -0.01  0.91      0.99     0.91    0.90
Sales Price       1.00         1.00     -0.01  0.91      0.99     0.91    0.90
Quantity         -0.01        -0.01      1.00  0.12      0.01     0.12    0.12
COGS              0.91         0.91      0.12  1.00      0.92     1.00    0.98
Discount          0.99         0.99      0.01  0.92      1.00     0.92    0.91
Revenue           0.91         0.91      0.12  1.00      0.92     1.00    0.99
Profit            0.90         0.90      0.12  0.98      0.91     0.99    1.00

In [13]:
# Calculate revenue using Sales Price and Quantity
df["Calculated Revenue"] = df["Sales Price"] * df["Quantity"]

# Compare calculated revenue with existing revenue
df["Revenue Difference"] = (
    df["Revenue"] - df["Calculated Revenue"]
)

# Display the first 10 rows
df[[
    "Sales Price",
    "Quantity",
    "Discount",
    "Revenue",
    "Calculated Revenue",
    "Revenue Difference"
]].head(10)

,Sales Price,Quantity,Discount,Revenue,Calculated Revenue,Revenue Difference
0,325,6,100.00,1950.0,1950,0.0
1,104,9,93.60,936.0,936,0.0
2,234,1,16.38,234.0,234,0.0
3,130,7,42.00,840.0,910,-70.0
4,52,3,7.80,156.0,156,0.0
5,130,6,39.00,780.0,780,0.0
6,234,7,81.90,1638.0,1638,0.0
7,104,3,31.20,312.0,312,0.0
8,117,6,49.14,702.0,702,0.0
9,26,5,8.40,120.0,130,-10.0

In [14]:
# Calculate profit using Revenue and COGS
df["Calculated Profit"] = df["Revenue"] - df["COGS"]

# Compare with existing Profit
df["Profit Difference"] = (
    df["Profit"] - df["Calculated Profit"]
)

df[[
    "Revenue",
    "COGS",
    "Profit",
    "Calculated Profit",
    "Profit Difference"
]].head(10)

   Revenue  COGS  Profit  Calculated Profit  Profit Difference
0   1950.0  1500   450.0              450.0                0.0
1    936.0   720   216.0              216.0                0.0
2    234.0   180    54.0               54.0                0.0
3    840.0   700   140.0              140.0                0.0
4    156.0   120    36.0               36.0                0.0
5    780.0   600   180.0              180.0                0.0
6   1638.0  1260   378.0              378.0                0.0
7    312.0   240    72.0               72.0                0.0
8    702.0   540   162.0              162.0                0.0
9    120.0   100    20.0               20.0                0.0

In [15]:
# Count rows where revenue doesn't match Sales Price * Quantity
(df["Revenue Difference"] != 0).sum()

np.int64(4899)

In [16]:
# Count matching and mismatching revenue records
df["Revenue Difference"].value_counts()

Revenue Difference
 0.0        5101
-2.0         146
-2.5         133
-3.0         127
-4.0         100
            ...
-5.4           1
-25000.0       1
-27000.0       1
-3675.0        1
-405.0         1
Name: count, Length: 338, dtype: int64

In [17]:
# Display records with revenue mismatches
df[df["Revenue Difference"] != 0][
    [
        "Product",
        "Sales Price",
        "Quantity",
        "Discount",
        "Revenue",
        "Calculated Revenue",
        "Revenue Difference"
    ]
].head(20)

,Product,Sales Price,Quantity,Discount,Revenue,Calculated Revenue,Revenue Difference
3,Energy Drink,130,7,42.000,840.0,910,-70.0
9,Packaged Water (1L),26,5,8.400,120.0,130,-10.0
11,Dish Soap,104,2,9.600,192.0,208,-16.0
14,Tea,715,1,34.375,687.5,715,-27.5
16,Juice (1L),117,7,90.720,756.0,819,-63.0
17,Shirt,1170,4,117.000,4500.0,4680,-180.0
19,Headphones,4550,6,455.000,26250.0,27300,-1050.0
22,Bluetooth Speaker,2860,6,286.000,16500.0,17160,-660.0
23,Coffee (200g),325,4,100.000,1150.0,1300,-150.0
24,Jeans,2340,5,234.000,10800.0,11700,-900.0
25,Energy Drink,130,5,40.250,575.0,650,-75.0
28,Pen,13,3,1.800,36.0,39,-3.0
31,Sanitary Pads,130,1,12.500,125.0,130,-5.0
32,Ruler,20,7,8.820,126.0,140,-14.0
37,Pencil,7,9,8.775,58.5,63,-4.5
39,Laptop,71500,3,9900.000,198000.0,214500,-16500.0
41,Tablet,23400,7,3510.000,144900.0,163800,-18900.0
42,Juice (1L),117,3,16.875,337.5,351,-13.5
46,Pants,1950,3,195.000,5400.0,5850,-450.0
47,Skirt,1040,2,104.000,2000.0,2080,-80.0

In [18]:
# Calculate revenue after subtracting discount
df["Revenue After Discount"] = (
    df["Sales Price"] * df["Quantity"] - df["Discount"]
)

# Compare calculated revenue with actual revenue
df["Discount Difference"] = (
    df["Revenue"] - df["Revenue After Discount"]
)

# Count matching records
(df["Discount Difference"].abs() < 0.01).sum()

np.int64(20)

In [19]:
# Count how many records still don't match
(df["Discount Difference"].abs() >= 0.01).sum()

np.int64(9980)

In [20]:
# Calculate profit from Revenue and COGS
df["Calculated Profit"] = df["Revenue"] - df["COGS"]

# Calculate the difference
df["Profit Difference"] = (
    df["Profit"] - df["Calculated Profit"]
)

# Count records that match
(df["Profit Difference"].abs() < 0.01).sum()

np.int64(10000)

In [21]:
# Count records that do not match
(df["Profit Difference"].abs() >= 0.01).sum()

np.int64(0)

In [22]:
# Calculate COGS from Unit Cost and Quantity
df["Calculated COGS"] = df["Unit Cost"] * df["Quantity"]

# Compare calculated COGS with recorded COGS
df["COGS Difference"] = (
    df["COGS"] - df["Calculated COGS"]
)

# Count matching records
(df["COGS Difference"].abs() < 0.01).sum()

np.int64(10000)

In [23]:
# Count records that don't match
(df["COGS Difference"].abs() >= 0.01).sum()

np.int64(0)

In [24]:
# Get summary statistics for Discount
df["Discount"].describe()

count    10000.000000
mean       584.740428
std       1791.818955
min          0.252000
25%         23.400000
50%         74.940000
75%        156.000000
max      10725.000000
Name: Discount, dtype: float64

In [25]:
# Display unique discount values
df["Discount"].nunique()

722

In [26]:
# Check the smallest and largest discounts
df["Discount"].min(), df["Discount"].max()

(0.252, 10725.0)

In [27]:
# Calculate gross sales before discount
df["Gross Sales"] = df["Sales Price"] * df["Quantity"]

# Calculate discount percentage
df["Discount Percentage"] = (
    df["Discount"] / df["Gross Sales"]
) * 100

# View the first 10 records
df[[
    "Sales Price",
    "Quantity",
    "Gross Sales",
    "Discount",
    "Discount Percentage",
    "Revenue"
]].head(10)

   Sales Price  Quantity  Gross Sales  Discount  Discount Percentage  Revenue
0          325         6         1950    100.00             5.128205   1950.0
1          104         9          936     93.60            10.000000    936.0
2          234         1          234     16.38             7.000000    234.0
3          130         7          910     42.00             4.615385    840.0
4           52         3          156      7.80             5.000000    156.0
5          130         6          780     39.00             5.000000    780.0
6          234         7         1638     81.90             5.000000   1638.0
7          104         3          312     31.20            10.000000    312.0
8          117         6          702     49.14             7.000000    702.0
9           26         5          130      8.40             6.461538    120.0

In [28]:
(df["Discount"] > df["Gross Sales"]).sum()

np.int64(0)

In [29]:
# Calculate the difference between gross sales and revenue
df["Revenue Reduction"] = df["Gross Sales"] - df["Revenue"]

# Compare the reduction with the recorded discount
df["Reduction Difference"] = (
    df["Revenue Reduction"] - df["Discount"]
)

# Display the first 10 records
df[[
    "Product",
    "Gross Sales",
    "Discount",
    "Revenue",
    "Revenue Reduction",
    "Reduction Difference"
]].head(10)

,Product,Gross Sales,Discount,Revenue,Revenue Reduction,Reduction Difference
0,Coffee (200g),1950,100.00,1950.0,0.0,-100.00
1,Fruits,936,93.60,936.0,0.0,-93.60
2,Shampoo,234,16.38,234.0,0.0,-16.38
3,Energy Drink,910,42.00,840.0,70.0,28.00
4,Bread,156,7.80,156.0,0.0,-7.80
5,Energy Drink,780,39.00,780.0,0.0,-39.00
6,Shampoo,1638,81.90,1638.0,0.0,-81.90
7,Fruits,312,31.20,312.0,0.0,-31.20
8,Juice (1L),702,49.14,702.0,0.0,-49.14
9,Packaged Water (1L),130,8.40,120.0,10.0,1.60

In [30]:
# Count records where revenue reduction equals discount
(
    df["Reduction Difference"].abs() < 0.01
).sum()

np.int64(20)

In [31]:
# Summarize revenue reduction patterns
df["Revenue Reduction"].describe()

count    10000.000000
mean       486.769510
std       3122.241664
min         -1.000000
25%          0.000000
50%          0.000000
75%         27.000000
max      82500.000000
Name: Revenue Reduction, dtype: float64

In [32]:
# Revenue equals Gross Sales
(df["Revenue Reduction"] == 0).sum()

np.int64(5101)

In [33]:
# Revenue is lower than Gross Sales
(df["Revenue Reduction"] > 0).sum()

np.int64(4727)

In [34]:
# Revenue is higher than Gross Sales
(df["Revenue Reduction"] < 0).sum()

np.int64(172)

In [35]:
# Count all revenue patterns
revenue_equal = (df["Revenue Reduction"] == 0).sum()

revenue_lower = (df["Revenue Reduction"] > 0).sum()

revenue_higher = (df["Revenue Reduction"] < 0).sum()

print("Revenue equals Gross Sales:", revenue_equal)
print("Revenue is lower:", revenue_lower)
print("Revenue is higher:", revenue_higher)

print("Total classified:", revenue_equal + revenue_lower + revenue_higher)

print("Total dataset rows:", len(df))

Revenue equals Gross Sales: 5101
Revenue is lower: 4727
Revenue is higher: 172
Total classified: 10000
Total dataset rows: 10000

In [36]:
df.nlargest(10, "Revenue Reduction")[
    [
        "Product",
        "Sales Price",
        "Quantity",
        "Gross Sales",
        "Discount",
        "Revenue",
        "Revenue Reduction",
        "COGS",
        "Profit"
    ]
]

,Product,Sales Price,Quantity,Gross Sales,Discount,Revenue,Revenue Reduction,COGS,Profit
1313,Laptop,71500,10,715000,10725.0,632500.0,82500.0,550000,82500.0
1804,Laptop,71500,10,715000,10725.0,632500.0,82500.0,550000,82500.0
5654,Laptop,71500,10,715000,10725.0,632500.0,82500.0,550000,82500.0
9384,Laptop,71500,10,715000,10725.0,632500.0,82500.0,550000,82500.0
1044,Laptop,71500,9,643500,10725.0,569250.0,74250.0,495000,74250.0
2343,Laptop,71500,8,572000,10725.0,506000.0,66000.0,440000,66000.0
3704,Laptop,71500,10,715000,10725.0,660000.0,55000.0,550000,110000.0
5785,Laptop,71500,9,643500,10725.0,594000.0,49500.0,495000,99000.0
7117,Laptop,71500,8,572000,10725.0,528000.0,44000.0,440000,88000.0
2460,Laptop,71500,7,500500,10725.0,462000.0,38500.0,385000,77000.0

In [37]:
# Summarize revenue reduction by product
product_reduction = (
    df.groupby("Product")["Revenue Reduction"]
    .agg(["count", "mean", "max"])
    .sort_values("max", ascending=False)
)

product_reduction.head(10)

                   count         mean      max
Product
Laptop               233  8769.313305  82500.0
Smartphone           233  3626.609442  30000.0
Tablet               241  2741.078838  27000.0
Monitor              259  1867.181467  18000.0
Smartwatch           223   836.322870   6000.0
Headphones           195   447.820513   3675.0
Shoes                170   375.294118   3000.0
Jacket               165   356.818182   3000.0
Bluetooth Speaker    237   376.877637   2640.0
Jeans                154   294.545455   1890.0

In [38]:
# Recalculate Revenue Reduction from the current data
df["Revenue Reduction"] = (
    df["Sales Price"] * df["Quantity"] - df["Revenue"]
)

# Check dataset size
print("Dataset rows:", len(df))

# Count revenue patterns
print("\nRevenue pattern counts:")

print(
    df["Revenue Reduction"]
    .gt(0)
    .sum(),
    "Revenue lower than Gross Sales"
)

print(
    df["Revenue Reduction"]
    .eq(0)
    .sum(),
    "Revenue equal to Gross Sales"
)

print(
    df["Revenue Reduction"]
    .lt(0)
    .sum(),
    "Revenue higher than Gross Sales"
)

# Verify total classified records
print(
    "Total classified:",
    (
        df["Revenue Reduction"].gt(0).sum()
        + df["Revenue Reduction"].eq(0).sum()
        + df["Revenue Reduction"].lt(0).sum()
    )
)

# Recalculate product-level statistics
product_reduction = (
    df.groupby("Product")["Revenue Reduction"]
    .agg(["count", "mean", "max"])
    .sort_values("max", ascending=False)
)

print("\nProduct-level revenue reduction:")
display(product_reduction)

Dataset rows: 10000

Revenue pattern counts:
4727 Revenue lower than Gross Sales
5101 Revenue equal to Gross Sales
172 Revenue higher than Gross Sales
Total classified: 10000

Product-level revenue reduction:

                     count         mean       max
Product
Laptop                 233  8769.313305  82500.00
Smartphone             233  3626.609442  30000.00
Tablet                 241  2741.078838  27000.00
Monitor                259  1867.181467  18000.00
Smartwatch             223   836.322870   6000.00
Headphones             195   447.820513   3675.00
Shoes                  170   375.294118   3000.00
Jacket                 165   356.818182   3000.00
Bluetooth Speaker      237   376.877637   2640.00
Jeans                  154   294.545455   1890.00
Pants                  161   219.409938   1800.00
Power Bank             275   188.945455   1620.00
Shirt                  185   164.675676   1215.00
Skirt                  170   109.176471    960.00
Charger                207   111.690821    840.00
Tea                    284    87.438380    825.00
Bralette               164    69.146341    720.00
T-shirt                141    81.914894    675.00
Cap                    165    47.727273    405.00
Laundry Basket          67    46.679104    315.00
USB Cable              216    46.817130    300.00
Deodorant              125    41.600000    300.00
Coffee (200g)          279    38.485663    300.00
Dustbin                 50    45.300000    270.00
Calculator              62    32.661290    250.00
Shampoo                119    29.268908    189.00
Cooking Oil            267    21.471910    189.00
Face Wash              117    25.576923    180.00
Detergent Powder        64    15.656250    162.00
Juice (1L)             295    16.184746    135.00
Energy Drink           262    14.503817    135.00
Socks                  163    14.754601    120.00
Sanitary Pads          112    12.901786    120.00
Fruits                 295    13.328814    108.00
Broom                   63    15.000000    108.00
Rice                   274    10.478102     90.00
Toothpaste             108    14.875000     88.50
Wheat Flour            276    10.792572     87.50
Stapler                 54     8.750000     84.00
Dish Soap               56    11.428571     72.00
Milk                   265     9.067925     72.00
Razor                  136    10.386029     67.50
Sugar                  291    10.925258     65.25
Notebook                61     8.073770     60.00
Toilet Cleaner          73    11.339041     60.00
Bread                  259     6.285714     48.00
Soft Drink (500ml)     271     6.302583     48.00
Marker                  54     7.583333     38.25
Folder                  61     4.745902     36.00
Packaged Water (1L)    287     3.675958     30.00
Soap                    92     6.133152     28.75
Salt                   270     3.425926     27.00
Toothbrush             112     6.140625     25.50
Ruler                   63     5.119048     16.00
Highlighter             59     1.966102     15.00
Pencil                  56     3.553571      9.00
Eggs                   293     0.487372      7.60
Pen                     49     1.306122      6.00
Eraser                  62     1.016935      3.85

In [39]:
# Recalculate Revenue Reduction using the current DataFrame
df["Revenue Reduction"] = (
    df["Sales Price"] * df["Quantity"] - df["Revenue"]
)

# Verify dataset size
print("Dataset shape:", df.shape)

# Recalculate revenue pattern counts
revenue_counts = {
    "Revenue lower": (df["Revenue Reduction"] > 0).sum(),
    "Revenue equal": (df["Revenue Reduction"] == 0).sum(),
    "Revenue higher": (df["Revenue Reduction"] < 0).sum()
}

print("\nRevenue pattern counts:")
print(revenue_counts)

print("\nTotal classified:", sum(revenue_counts.values()))

# Verify product-level statistics
product_check = (
    df.groupby("Product")["Revenue Reduction"]
    .agg(["count", "min", "mean", "max"])
)

display(product_check)

print(
    "\nTotal product records:",
    product_check["count"].sum()
)

Dataset shape: (10000, 28)

Revenue pattern counts:
{'Revenue lower': np.int64(4727), 'Revenue equal': np.int64(5101), 'Revenue higher': np.int64(172)}

Total classified: 10000

                     count  min         mean       max
Product
Bluetooth Speaker      237  0.0   376.877637   2640.00
Bralette               164  0.0    69.146341    720.00
Bread                  259  0.0     6.285714     48.00
Broom                   63  0.0    15.000000    108.00
Calculator              62  0.0    32.661290    250.00
Cap                    165  0.0    47.727273    405.00
Charger                207  0.0   111.690821    840.00
Coffee (200g)          279  0.0    38.485663    300.00
Cooking Oil            267  0.0    21.471910    189.00
Deodorant              125  0.0    41.600000    300.00
Detergent Powder        64  0.0    15.656250    162.00
Dish Soap               56  0.0    11.428571     72.00
Dustbin                 50  0.0    45.300000    270.00
Eggs                   293 -1.0     0.487372      7.60
Energy Drink           262  0.0    14.503817    135.00
Eraser                  62  0.1     1.016935      3.85
Face Wash              117  0.0    25.576923    180.00
Folder                  61  0.0     4.745902     36.00
Fruits                 295  0.0    13.328814    108.00
Headphones             195  0.0   447.820513   3675.00
Highlighter             59  0.0     1.966102     15.00
Jacket                 165  0.0   356.818182   3000.00
Jeans                  154  0.0   294.545455   1890.00
Juice (1L)             295  0.0    16.184746    135.00
Laptop                 233  0.0  8769.313305  82500.00
Laundry Basket          67  0.0    46.679104    315.00
Marker                  54  0.5     7.583333     38.25
Milk                   265  0.0     9.067925     72.00
Monitor                259  0.0  1867.181467  18000.00
Notebook                61  0.0     8.073770     60.00
Packaged Water (1L)    287  0.0     3.675958     30.00
Pants                  161  0.0   219.409938   1800.00
Pen                     49  0.0     1.306122      6.00
Pencil                  56  1.0     3.553571      9.00
Power Bank             275  0.0   188.945455   1620.00
Razor                  136  0.0    10.386029     67.50
Rice                   274  0.0    10.478102     90.00
Ruler                   63  0.5     5.119048     16.00
Salt                   270  0.0     3.425926     27.00
Sanitary Pads          112  0.0    12.901786    120.00
Shampoo                119  0.0    29.268908    189.00
Shirt                  185  0.0   164.675676   1215.00
Shoes                  170  0.0   375.294118   3000.00
Skirt                  170  0.0   109.176471    960.00
Smartphone             233  0.0  3626.609442  30000.00
Smartwatch             223  0.0   836.322870   6000.00
Soap                    92  0.5     6.133152     28.75
Socks                  163  0.0    14.754601    120.00
Soft Drink (500ml)     271  0.0     6.302583     48.00
Stapler                 54  0.0     8.750000     84.00
Sugar                  291  0.5    10.925258     65.25
T-shirt                141  0.0    81.914894    675.00
Tablet                 241  0.0  2741.078838  27000.00
Tea                    284  0.0    87.438380    825.00
Toilet Cleaner          73  0.5    11.339041     60.00
Toothbrush             112  0.5     6.140625     25.50
Toothpaste             108  1.0    14.875000     88.50
USB Cable              216  0.0    46.817130    300.00
Wheat Flour            276  0.5    10.792572     87.50

Total product records: 10000

In [40]:
# Create a working copy for our AI analytics project
df_ai = df.copy()

# Save the working dataset
df_ai.to_csv("supermarket_ai_data.csv", index=False)

print("Dataset saved successfully!")
print("Rows:", df_ai.shape[0])
print("Columns:", df_ai.shape[1])

Dataset saved successfully!
Rows: 10000
Columns: 28

In [41]:
print(df.columns.tolist())

['Date', 'City', 'Country', 'Customer Type', 'Gender', 'Product Category', 'Product', 'SKU', 'Unit Cost', 'Sales Price', 'Quantity', 'COGS', 'Discount', 'Payment Method', 'Revenue', 'Profit', 'Calculated Revenue', 'Revenue Difference', 'Calculated Profit', 'Profit Difference', 'Revenue After Discount', 'Discount Difference', 'Calculated COGS', 'COGS Difference', 'Gross Sales', 'Discount Percentage', 'Revenue Reduction', 'Reduction Difference']

In [42]:
for i, col in enumerate(df.columns, 1):
    print(i, col)

1 Date
2 City
3 Country
4 Customer Type
5 Gender
6 Product Category
7 Product
8 SKU
9 Unit Cost
10 Sales Price
11 Quantity
12 COGS
13 Discount
14 Payment Method
15 Revenue
16 Profit
17 Calculated Revenue
18 Revenue Difference
19 Calculated Profit
20 Profit Difference
21 Revenue After Discount
22 Discount Difference
23 Calculated COGS
24 COGS Difference
25 Gross Sales
26 Discount Percentage
27 Revenue Reduction
28 Reduction Difference